apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  ports:
    - port: 9002
      targetPort: 9002
      nodePort: // add the nodeport here above 31000
  selector:
    app: api

//changes