version: "3.8"
services:
  api:
    image: saada865/fypdev-api:v1.0
    container_name: api_c
    ports:
      - '9002:9002'
    volumes:
      - api_node_modules:/app/node_modules

  frontend:
    image: saada865/fypdev-frontend:v1.0
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes:
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  api_node_modules:
  frontend_node_modules:
